# Adapted from https://github.com/bazelbuild/rules_go/blob/master/.travis.yml

# trusty beta image has jdk8, gcc4.8.4
dist: trusty
sudo: required
# xcode8 has jdk8
osx_image: xcode8.3
# Not technically required but suppresses 'Ruby' in Job status message.
language: java

os:
  - linux

env:
  # TODO(bazelbuild/continuous-integration#95): re-enable HEAD builds with stable URL
  # - V=HEAD
  - V=0.14.1

before_install:
  - |
    sysctl kernel.unprivileged_userns_clone=1
    OS=linux
    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --config=ci \
      --experimental_repository_cache="$HOME/.bazel_repository_cache" \
      --local_resources=400,1,1.0 \
      --test_tag_filters=-dev \
      //...
